---
- name: Ensure directories are present
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ oracle_user }}"
    group: oinstall
    mode: '0755'
  with_items:
    - "{{ oracle_home }}"
    - "{{ oracle_base }}"
    - "{{ download_dir }}"

