---
# tasks file for nfs_mount

- name: Ensure mount point directory exists
  file:
    path: "{{ mount_point }}"
    state: directory

- name: Mount NFS share
  mount:
    src: "{{ nfs_server }}:{{ nfs_share }}"
    path: "{{ mount_point }}"
    fstype: nfs
    opts: defaults
    state: mounted

- name: Ensure NFS share is mounted at boot
  mount:
    src: "{{ nfs_server }}:{{ nfs_share }}"
    path: "{{ mount_point }}"
    fstype: nfs
    opts: defaults
    state: present

